[package]
name = "ic-mockery"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Dan B (@0xVersion)"]
repository = "https://github.com/liquidium/ic-mockery"

resolver = "2"

[lib]
crate-type = ["rlib"]

[lints.clippy]
type_complexity = "allow"


[dependencies]
pocket-ic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
candid = { workspace = true }

[dev-dependencies]
canister = { path = "../../canister" }
